"""Artifact generation: CSV, JSON, PNG, and Markdown report.

All I/O happens here - writes simulation results to disk.
"""

import json
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from valuation_pathways.engine.simulator import SimulationResult


def write_artifacts(
    result: SimulationResult,
    outdir: str | Path,
    V0: float,
    months: int,
) -> None:
    """Write all simulation artifacts to output directory.
    
    Creates:
        - results.csv: Full simulation data
        - summary.json: Summary statistics
        - hist.png: Overlaid histograms
        - report.md: Markdown report
    
    Args:
        result: SimulationResult from engine
        outdir: Output directory path
        V0: Initial valuation (for report context)
        months: Simulation horizon (for report context)
    """
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    
    # Write results CSV
    result.final_values.to_csv(outdir / "results.csv", index=False)
    
    # Write summary JSON
    with open(outdir / "summary.json", "w") as f:
        json.dump(result.summary, f, indent=2)
    
    # Generate histogram
    _write_histogram(result, outdir / "hist.png", V0)
    
    # Generate markdown report
    _write_report(result, outdir / "report.md", V0, months)


def _write_histogram(result: SimulationResult, path: Path, V0: float) -> None:
    """Generate overlaid histograms of final valuations by scenario."""
    fig, ax = plt.subplots(figsize=(10, 6))
    
    scenarios = result.final_values["scenario"].unique()
    colors = plt.cm.Set2(range(len(scenarios)))
    
    for scenario, color in zip(scenarios, colors):
        data = result.final_values[result.final_values["scenario"] == scenario]["V_T"]
        ax.hist(
            data,
            bins=30,
            alpha=0.6,
            label=scenario,
            color=color,
            edgecolor="black",
            linewidth=0.5,
        )
    
    # Add V0 reference line
    ax.axvline(V0, color="red", linestyle="--", linewidth=2, label=f"V₀ = {V0:.2f}M")
    
    ax.set_xlabel("Final Valuation V_T (millions)", fontsize=12)
    ax.set_ylabel("Frequency", fontsize=12)
    ax.set_title("Distribution of Final Valuations by Scenario", fontsize=14, fontweight="bold")
    ax.legend(fontsize=10)
    ax.grid(alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()


def _write_report(
    result: SimulationResult,
    path: Path,
    V0: float,
    months: int,
) -> None:
    """Generate markdown report summarizing simulation."""
    lines = [
        "# Valuation Pathway Simulation Report",
        "",
        "## Model",
        "",
        "**Discrete-time regime-switching log-value dynamics:**",
        "",
        "```",
        "log V_{t+1} = log V_t + μ_{s_t} + σ_{s_t} * ε_t",
        "```",
        "",
        "where:",
        "- `V_t` is the valuation at time t",
        "- `s_t` is the regime at time t",
        "- `μ_{s_t}` is the regime-specific monthly log-drift",
        "- `σ_{s_t}` is the regime-specific monthly log-volatility",
        "- `ε_t ~ N(0, 1)` is standard normal noise",
        "",
        "## Simulation Parameters",
        "",
        f"- **Initial Valuation (V₀):** {V0:.2f} million",
        f"- **Horizon:** {months} months",
        f"- **Simulations per scenario:** {len(result.final_values) // len(result.summary)}",
        "",
        "## Summary Statistics",
        "",
        "| Scenario | Mean | P10 | P50 | P90 | Prob(V_T < V₀) |",
        "|----------|------|-----|-----|-----|----------------|",
    ]
    
    for scenario_name, metrics in result.summary.items():
        lines.append(
            f"| {scenario_name} | "
            f"{metrics['mean']:.3f} | "
            f"{metrics['p10']:.3f} | "
            f"{metrics['p50']:.3f} | "
            f"{metrics['p90']:.3f} | "
            f"{metrics['prob_down']:.2%} |"
        )
    
    lines.extend([
        "",
        "## Distribution of Final Valuations",
        "",
        "![Valuation Distribution](hist.png)",
        "",
        "---",
        "",
        "*Generated by Valuation Pathway Simulator*",
    ])
    
    with open(path, "w") as f:
        f.write("\n".join(lines))
